import {auth,db,onAuthStateChanged,signInWithEmailAndPassword,signOut,collection,doc,setDoc,getDocs,serverTimestamp} from './firebase.js';import * as M from './mqtt.js';
const I={ar:{appSubtitle:'التحكم الذكي في الزراعة المائية',monitoring:'المراقبة',quickControl:'التحكم السريع',airTemp:'حرارة الهواء',data:'البيانات',control:'التحكم',alerts:'التنبيهات',settings:'الإعدادات',systemMode:'وضع النظام',language:'اللغة',theme:'المظهر',mqttPassword:'كلمة مرور MQTT',rememberMqtt:'تذكر كلمة المرور على هذا الجهاز',saveConnect:'حفظ والاتصال',logout:'تسجيل الخروج',home:'الرئيسية',growth:'نمو النباتات',growthSubtitle:'متابعة المراحل والتذكيرات والتسجيل اليدوي',newGroup:'مجموعة جديدة'},en:{appSubtitle:'Smart hydroponic control',monitoring:'Monitoring',quickControl:'Quick control',airTemp:'Air Temperature',data:'Data',control:'Control',alerts:'Alerts',settings:'Settings',systemMode:'System mode',language:'Language',theme:'Theme',mqttPassword:'MQTT password',rememberMqtt:'Remember password on this device',saveConnect:'Save & Connect',logout:'Sign out',home:'Home',growth:'Plant Growth',growthSubtitle:'Stages, reminders and manual records',newGroup:'New Group'},fr:{appSubtitle:'Contrôle hydroponique intelligent',monitoring:'Surveillance',quickControl:'Contrôle rapide',airTemp:'Température de l’air',data:'Données',control:'Contrôle',alerts:'Alertes',settings:'Paramètres',systemMode:'Mode système',language:'Langue',theme:'Thème',mqttPassword:'Mot de passe MQTT',rememberMqtt:'Mémoriser sur cet appareil',saveConnect:'Enregistrer et connecter',logout:'Déconnexion',home:'Accueil',growth:'Croissance des plantes',growthSubtitle:'Étapes, rappels et relevés manuels',newGroup:'Nouveau groupe'}};
let lang=localStorage.getItem('hydro_lang')||'ar',mode=localStorage.getItem('hydro_mode')||'AUTO',tele={airTemperature:null,airHumidity:null,waterTemperature:null,waterLevel:null,ph:null,ec:null},history=[];const limits={airTemperature:[28,30],airHumidity:[75,80],waterTemperature:[18,28],waterLevel:[20,40]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}function t(k){return I[lang][k]||I.ar[k]||k}function applyLang(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';$$('[data-i18n]').forEach(e=>e.textContent=t(e.dataset.i18n));$('#language').value=lang;localStorage.setItem('hydro_lang',lang)}
function page(p){$$('.page').forEach(e=>e.classList.toggle('active',e.id===p));$$('.nav').forEach(e=>e.classList.toggle('active',e.dataset.page===p));if(p==='growth')loadGroups()}$$('.nav').forEach(b=>b.onclick=()=>page(b.dataset.page));$$('[data-open]').forEach(b=>b.onclick=()=>page(b.dataset.open));$$('[data-back]').forEach(b=>b.onclick=()=>page(b.dataset.back));
function gauge(key,label,icon,unit,min,max){const v=tele[key];let pct=v==null?0:Math.max(0,Math.min(100,(v-min)/(max-min)*100));const bad=v!=null&&((key==='airTemperature'&&v>=limits.airTemperature[1])||(key==='airHumidity'&&v>=limits.airHumidity[1])||(key==='waterTemperature'&&v>=limits.waterTemperature[1])||(key==='waterLevel'&&v<=limits.waterLevel[0]));return `<article class="gauge-card ${bad?'danger-gauge':''}"><div class="gauge" style="--pct:${pct}%;--gcolor:${bad?'var(--red)':key==='airTemperature'?'var(--orange)':'var(--green)'}"><div class="gauge-inner"><div class="gauge-value">${v==null?'—':Number(v).toFixed(key==='airHumidity'||key==='waterLevel'?0:1)}${v==null?'':unit}</div></div></div><div class="gauge-label">${icon} ${label}</div><div class="gauge-status">${bad?'⚠️ '+(lang==='ar'?'خارج النطاق':lang==='fr'?'Hors plage':'Out of range'):v==null?'—':lang==='ar'?'طبيعي':lang==='fr'?'Normal':'Normal'}</div></article>`}
function render(){const g=$('#gauges');g.innerHTML=gauge('airTemperature',t('airTemp'),'🌡️','°C',10,45)+gauge('airHumidity',lang==='ar'?'الرطوبة':lang==='fr'?'Humidité':'Humidity','💧','%',0,100)+gauge('waterTemperature',lang==='ar'?'حرارة الماء':lang==='fr'?'Température de l’eau':'Water Temperature','🌊','°C',5,40)+gauge('waterLevel',lang==='ar'?'مستوى الخزان':lang==='fr'?'Niveau du réservoir':'Water Level','💦','%',0,100)+gauge('ph','pH','🧪','',3,10)+gauge('ec','EC','⚡','',0,4);$('#modeBadge').textContent=mode;$('#modeBadge').className='badge '+(mode==='MANUAL'?'manual':'auto');$('#controls').innerHTML=devices().map(d=>`<div class="device panel"><div><b>${d.icon} ${d.name}</b><small>${d.sub}</small></div><button class="switch ${d.on?'on':''}" data-device="${d.id}"></button></div>`).join('');$('#quickDevices').innerHTML=devices().slice(0,3).map(d=>`<div class="quick-row"><span>${d.icon} ${d.name}</span><button class="switch ${d.on?'on':''}" data-device="${d.id}"></button></div>`).join('');$$('[data-device]').forEach(b=>b.onclick=()=>toggleDevice(b.dataset.device));$('#userEmail').textContent=auth.currentUser?.email||'—';applyLang()}
function devices(){return[{id:'pump1',name:'Pump 1 — NFT',sub:'ON/OFF cycle',icon:'💧',on:false},{id:'pump2',name:'Pump 2 — Venturi',sub:'ON/OFF cycle',icon:'🌀',on:false},{id:'pump3',name:'Pump 3 — Tank Fill',sub:'20% ON / 40% OFF',icon:'🚰',on:false},{id:'pump4',name:'Pump 4 — Pad Cooling',sub:'Temperature + Humidity',icon:'❄️',on:false},{id:'fan1',name:'Fan 1',sub:'Temperature + Humidity',icon:'🌀',on:false},{id:'fan2',name:'Fan 2',sub:'ON/OFF cycle',icon:'🌀',on:false}]}
function toggleDevice(id){if(mode==='AUTO'){toast(lang==='ar'?'النظام في AUTO — انتقل إلى MANUAL أولًا':lang==='fr'?'Le système est en AUTO — passez en MANUAL':'System is AUTO — switch to MANUAL first');return}if(!M.publish({type:'device',device:id,state:'TOGGLE'}))toast(lang==='ar'?'MQTT غير متصل': 'MQTT offline')}
$('#autoBtn').onclick=()=>setMode('AUTO');$('#manualBtn').onclick=()=>{showConfirm(()=>setMode('MANUAL'))};function setMode(m){mode=m;localStorage.setItem('hydro_mode',m);M.publish({type:'mode',mode:m});render();toast(m==='AUTO'?(lang==='ar'?'تم تفعيل AUTO':'AUTO enabled'):(lang==='ar'?'تم تفعيل MANUAL':'MANUAL enabled'))}function showConfirm(ok){$('#modal').innerHTML=`<div class="modal-box"><h3>⚠️ ${lang==='ar'?'التحكم اليدوي':lang==='fr'?'Contrôle manuel':'Manual control'}</h3><p>${lang==='ar'?'تأكد من أن تشغيل الأجهزة آمن.':lang==='fr'?'Assurez-vous que le fonctionnement est sûr.':'Make sure operating the devices is safe.'}</p><div class="modal-actions"><button class="danger" id="cancel">${lang==='ar'?'إلغاء':'Cancel'}</button><button class="primary" id="continue">${lang==='ar'?'متابعة':'Continue'}</button></div></div>`;$('#modal').classList.remove('hidden');$('#modal').style.display='grid';$('#cancel').onclick=closeModal;$('#continue').onclick=()=>{closeModal();ok()}}function closeModal(){const m=$('#modal');m.classList.add('hidden');m.style.display='none'}
window.addEventListener('mqtt-status',e=>{const c=e.detail.connected;$('#mqttDot').className='dot '+(c?'on':'off');$('#mqttState').textContent=c?(lang==='ar'?'متصل بـ MQTT':'MQTT Connected'):(e.detail.needsPassword?(lang==='ar'?'أدخل كلمة مرور MQTT':'Enter MQTT password'):(lang==='ar'?'غير متصل':'Offline'));if(c)toast(lang==='ar'?'تم الاتصال بـ HiveMQ':'Connected to HiveMQ')});window.addEventListener('mqtt-message',e=>{if(e.detail.topic===M.TOPICS.sensors){tele={...tele,...e.detail.data};history.push({...tele,time:new Date()});if(history.length>100)history.shift();$('#lastUpdate').textContent=(lang==='ar'?'آخر تحديث ':'Last update ')+new Date().toLocaleTimeString();render()}});
$('#mqttSave').onclick=()=>{const p=$('#mqttPassword').value;if(!p&& !M.password()){toast(lang==='ar'?'أدخل كلمة مرور MQTT أولًا':'Enter MQTT password first');return}M.save(p||M.password(),$('#mqttRemember').checked);M.connect()};$('#language').onchange=e=>{lang=e.target.value;applyLang();render()};$('#theme').onchange=e=>{localStorage.setItem('hydro_theme',e.target.value);applyTheme()};function applyTheme(){const x=localStorage.getItem('hydro_theme')||'system';document.body.classList.toggle('dark',x==='dark'||(x==='system'&&matchMedia('(prefers-color-scheme: dark)').matches))}$('#logout').onclick=()=>signOut(auth);
function showLogin(){
  let overlay=document.getElementById('loginOverlay');
  if(!overlay){
    overlay=document.createElement('div');
    overlay.id='loginOverlay';
    overlay.className='modal';
    document.body.appendChild(overlay);
  }
  overlay.innerHTML=`<div class="modal-box"><h2>🌱 Hydroponic Control</h2><p>${lang==='ar'?'تسجيل الدخول':'Sign in'}</p><label>Email<input id="loginEmail" type="email" autocomplete="email"></label><label>Password<input id="loginPass" type="password" autocomplete="current-password"></label><button id="loginBtn" class="primary full">${lang==='ar'?'دخول':'Sign in'}</button><p id="loginErr" class="hint"></p></div>`;
  overlay.classList.remove('hidden');
  document.getElementById('app').style.display='none';
  $('#loginBtn').onclick=async()=>{
    const email=$('#loginEmail').value.trim(), password=$('#loginPass').value;
    if(!email||!password){$('#loginErr').textContent=lang==='ar'?'أدخل البريد وكلمة المرور':'Enter email and password';return}
    $('#loginBtn').disabled=true;
    try{await signInWithEmailAndPassword(auth,email,password)}
    catch(e){$('#loginErr').textContent=(e.code||e.message);$('#loginBtn').disabled=false}
  };
}
function hideLogin(){const overlay=document.getElementById('loginOverlay');if(overlay)overlay.classList.add('hidden');document.getElementById('app').style.display='block'}
const veg=[['seed','البذرة',1],['germination','الإنبات',5],['transplant','التشتيل',12],['vegetative','النمو الخضري',45],['harvest','الحصاد',0]],fruit=[['seed','البذرة',1],['germination','الإنبات',5],['transplant','التشتيل',12],['vegetative','النمو الخضري',45],['flowering','التزهير',20],['fruiting','الإثمار',30],['harvest','الحصاد',0]];
const growthState={groups:[],selected:null,records:[],recordRange:'all'};
const todayISO=()=>new Date().toISOString().slice(0,10);
const fmtDate=d=>{if(!d)return '—';const x=new Date(d+'T00:00:00');return x.toLocaleDateString(lang==='ar'?'ar-TN':lang==='fr'?'fr-FR':'en-US',{year:'numeric',month:'short',day:'numeric'});};
const stageTemplate=type=>(type==='fruit'?fruit:veg).map(x=>({key:x[0],name:x[1],days:x[2]}));
function growthStages(g){return Array.isArray(g.stages)?g.stages:stageTemplate(g.type).map(x=>({name:x.name,days:x.days}));}
function stageDates(g){const seed=new Date((g.seedDate||todayISO())+'T00:00:00');let cursor=new Date(seed);return growthStages(g).map((s,i)=>{const start=new Date(cursor);const days=Math.max(0,Number(s.days)||0);const end=new Date(start);if(days>0)end.setDate(end.getDate()+days-1);cursor=new Date(end);cursor.setDate(cursor.getDate()+1);return {...s,start:start.toISOString().slice(0,10),end:end.toISOString().slice(0,10),index:i};});}
function currentStage(g){if(g.status==='harvested')return {index:growthStages(g).length-1,name:'الحصاد',progress:100,done:true};const ds=stageDates(g), now=new Date(todayISO()+'T00:00:00');let idx=ds.findIndex(s=>now>=new Date(s.start+'T00:00:00')&&now<=new Date(s.end+'T00:00:00'));if(idx<0){if(now<new Date(ds[0].start+'T00:00:00'))idx=0;else idx=ds.length-1;}const st=ds[idx], total=Math.max(1,Math.ceil((new Date(st.end+'T00:00:00')-new Date(st.start+'T00:00:00'))/86400000)+1);const elapsed=Math.min(total,Math.max(1,Math.floor((now-new Date(st.start+'T00:00:00'))/86400000)+1));return {index:idx,name:st.name,start:st.start,end:st.end,progress:Math.round(elapsed/total*100),done:idx===ds.length-1};}
function growthSummary(g){const ds=stageDates(g), cur=currentStage(g);const total=ds.reduce((a,s)=>a+Math.max(0,Number(s.days)||0),0);const passed=Math.max(0,Math.floor((new Date(todayISO()+'T00:00:00')-new Date((g.seedDate||todayISO())+'T00:00:00'))/86400000));return {ds,cur,total,passed,harvest:ds.at(-1)?.end||g.seedDate};}
function activeGroups(){return growthState.groups.filter(g=>g.status!=='harvested');}
function archivedGroups(){return growthState.groups.filter(g=>g.status==='harvested');}
async function loadGroups(){
  if(!auth.currentUser)return;
  try{const snap=await getDocs(collection(db,'users',auth.currentUser.uid,'growthGroups'));const arr=[];snap.forEach(x=>arr.push({id:x.id,...x.data()}));growthState.groups=arr;renderGrowthList();}
  catch(e){console.error(e);$('#groups').innerHTML='<div class="panel">تعذر تحميل مجموعات Growth: '+(e.code||e.message)+'</div>';}
}
function renderGrowthList(){
  const active=activeGroups(), archived=archivedGroups();
  const activeHtml=active.map(g=>{const s=growthSummary(g);return `<div class="growth-card group"><div class="growth-card-head"><div><h3>🌱 ${escapeHtml(g.name||'مجموعة')}</h3><small>${g.type==='fruit'?'🍅 نبات مثمر':'🥬 نبات خضري'} · ${fmtDate(g.seedDate)}</small></div><span class="growth-pill">${escapeHtml(s.cur.name)}</span></div><div class="progress"><span style="width:${s.cur.progress}%"></span></div><div class="growth-meta"><span>${lang==='ar'?'المرحلة الحالية':'Current stage'}: <b>${escapeHtml(s.cur.name)}</b></span><span>${s.cur.progress}%</span></div><div class="growth-dates"><span>🌱 ${fmtDate(g.seedDate)}</span><span>🥬 ${fmtDate(s.harvest)}</span></div><div class="growth-actions"><button class="primary" data-growth-open="${g.id}">فتح المجموعة</button><button class="secondary" data-growth-edit="${g.id}">✏️ تعديل</button></div></div>`}).join('')||'<div class="panel empty">لا توجد مجموعات نشطة بعد.</div>';
  const archivedHtml=archived.length?`<div class="growth-section-title"><h2>📚 Previous Crops</h2><small>${archived.length} ${lang==='ar'?'محصول محفوظ':'archived crops'}</small></div>`+archived.map(g=>`<div class="group archived"><div class="growth-card-head"><div><h3>📚 ${escapeHtml(g.name||'مجموعة')}</h3><small>تم الحصاد: ${fmtDate(g.harvestDate||g.seedDate)}</small></div><span class="growth-pill done">✓ ${lang==='ar'?'محصود':'Harvested'}</span></div><div class="growth-actions"><button class="primary" data-growth-open="${g.id}">فتح السجل</button><button class="danger" data-growth-delete="${g.id}">حذف</button></div></div>`).join(''):'';
  $('#groups').innerHTML=`<div class="growth-section-title"><h2>🌱 Active Crops</h2><small>${active.length} ${lang==='ar'?'مجموعة':'groups'}</small></div>${activeHtml}${archivedHtml}`;
}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function groupModal(group=null){
  const isEdit=!!group;const type=group?.type||'vegetable';const stages=(group?.stages||stageTemplate(type).map(x=>({name:x.name,days:x.days}))).map((x,i)=>({name:x.name,days:Number(x.days)||0,key:x.key||'custom'}));
  $('#modal').innerHTML=`<div class="modal-box growth-modal"><div class="modal-top"><h2>🌱 ${isEdit?'تعديل المجموعة':'مجموعة جديدة'}</h2><button class="modal-x" id="gClose">×</button></div><label>اسم المجموعة<input id="gName" value="${escapeHtml(group?.name||'مجموعة جديدة')}"></label><label>نوع النبات<select id="gType"><option value="vegetable" ${type==='vegetable'?'selected':''}>🥬 نبات خضري</option><option value="fruit" ${type==='fruit'?'selected':''}>🍅 نبات مثمر</option></select></label><label>تاريخ وضع البذرة<input id="gDate" type="date" value="${group?.seedDate||todayISO()}"></label><label>وقت التذكير اليومي<input id="gTime" type="time" value="${group?.reminderTime||'09:00'}"></label><label class="check"><input id="gReminder" type="checkbox" ${group?.reminderEnabled!==false?'checked':''}> تفعيل التذكير اليومي</label><div class="section-mini"><b>مراحل النمو</b><small>يمكن تعديل المدة وإضافة أو حذف أي مرحلة.</small></div><div id="stageEditor"></div><button id="addStage" class="secondary full">＋ إضافة مرحلة</button><div class="modal-actions"><button id="gCancel" class="danger">إلغاء</button><button id="gSave" class="primary">${isEdit?'حفظ التعديلات':'حفظ'}</button></div><p id="gErr" class="hint"></p></div>`;
  $('#modal').classList.remove('hidden');$('#modal').style.display='grid';
  const editor=$('#stageEditor');
  function draw(){editor.innerHTML=stages.map((x,i)=>`<div class="stage-editor-row"><span>${i+1}</span><input class="stageName" value="${escapeHtml(x.name)}"><input class="stageDays" type="number" min="0" value="${x.days}"><button class="icon-mini" data-stage-remove="${i}" ${stages.length<=1?'disabled':''}>×</button></div>`).join('');}
  draw();
  $('#gType').onchange=e=>{if(!isEdit){stages.splice(0,stages.length,...stageTemplate(e.target.value).map(x=>({name:x[1],days:x[2],key:x[0]})));draw();}};
  $('#addStage').onclick=()=>{stages.splice(stages.length-1,0,{name:'مرحلة جديدة',days:1,key:'custom'});draw();};
  editor.onclick=e=>{const b=e.target.closest('[data-stage-remove]');if(!b)return;stages.splice(Number(b.dataset.stageRemove),1);draw();};
  $('#gClose').onclick=closeModal;$('#gCancel').onclick=closeModal;$('#gSave').onclick=()=>saveGroup(group?.id||null,stages);
}
// Public handler used by the New Group button.
window.openNewGroup=()=>{try{groupModal(null);}catch(e){console.error('openNewGroup failed:',e);toast('تعذر فتح نافذة إنشاء المجموعة');}};
async function saveGroup(id,stageBuffer){const err=$('#gErr');try{if(!auth.currentUser)throw new Error('NOT_AUTHENTICATED');const stages=$$('.stage-editor-row').map((row,i)=>({name:row.querySelector('.stageName').value.trim()||`مرحلة ${i+1}`,days:Math.max(0,Number(row.querySelector('.stageDays').value)||0)}));const data={name:$('#gName').value.trim()||'مجموعة',type:$('#gType').value,seedDate:$('#gDate').value||todayISO(),reminderTime:$('#gTime').value||'09:00',reminderEnabled:$('#gReminder').checked,stages,updatedAt:serverTimestamp(),ownerUid:auth.currentUser.uid,status:id?(growthState.groups.find(g=>g.id===id)?.status||'active'):'active'};if(!id){id=crypto.randomUUID();data.createdAt=serverTimestamp();}await setDoc(doc(db,'users',auth.currentUser.uid,'growthGroups',id),data,{merge:true});closeModal();toast(id&&growthState.groups.some(g=>g.id===id)?'تم تحديث المجموعة بنجاح':'تم حفظ المجموعة بنجاح');await loadGroups();}catch(e){err.textContent=(lang==='ar'?'فشل الحفظ: ':'Save failed: ')+(e.code||e.message);console.error(e);}}
async function openGrowthGroup(id){const g=growthState.groups.find(x=>x.id===id);if(!g)return;growthState.selected=g;growthState.records=await loadRecords(id);renderGrowthDetail(g);}
async function loadRecords(id){const out=[];try{const snap=await getDocs(collection(db,'users',auth.currentUser.uid,'growthGroups',id,'records'));snap.forEach(x=>out.push({id:x.id,...x.data()}));out.sort((a,b)=>String(b.date).localeCompare(String(a.date)));}catch(e){console.error(e)}return out;}
function renderGrowthDetail(g){const s=growthSummary(g),ds=s.ds;$('#modal').innerHTML=`<div class="modal-box growth-detail"><div class="modal-top"><div><h2>🌱 ${escapeHtml(g.name)}</h2><small>${g.type==='fruit'?'🍅 نبات مثمر':'🥬 نبات خضري'} · ${fmtDate(g.seedDate)}</small></div><button class="modal-x" id="detailClose">×</button></div><div class="detail-hero"><div><small>المرحلة الحالية</small><strong>${escapeHtml(s.cur.name)}</strong></div><div class="big-progress" style="--p:${s.cur.progress}%"><span>${s.cur.progress}%</span></div></div><div class="growth-dates"><span>🌱 ${fmtDate(g.seedDate)}</span><span>🥬 ${fmtDate(s.harvest)}</span></div><div class="detail-tabs"><button class="sel" data-detail-tab="overview">نظرة عامة</button><button data-detail-tab="log">🧪 السجل اليومي</button><button data-detail-tab="reminder">⏰ التذكير</button></div><div id="detailContent"></div></div>`;$('#modal').classList.remove('hidden');$('#modal').style.display='grid';$('#detailClose').onclick=closeModal;const renderTab=tab=>{ $$('.detail-tabs button').forEach(b=>b.classList.toggle('sel',b.dataset.detailTab===tab)); if(tab==='overview')renderOverview(g,s,ds);else if(tab==='log')renderLog(g);else renderReminder(g);};$('.detail-tabs').onclick=e=>{const b=e.target.closest('[data-detail-tab]');if(b)renderTab(b.dataset.detailTab)};renderTab('overview');}
function renderOverview(g,s,ds){$('#detailContent').innerHTML=`<div class="section-mini"><b>📋 مراحل النمو</b></div><div class="timeline">${ds.map((x,i)=>`<div class="timeline-row ${i===s.cur.index?'current':''} ${i<s.cur.index?'passed':''}"><span class="timeline-dot">${i<s.cur.index?'✓':i===s.cur.index?'●':'○'}</span><div><b>${escapeHtml(x.name)}</b><small>${fmtDate(x.start)} → ${fmtDate(x.end)} · ${x.days} يوم</small></div></div>`).join('')}</div><div class="detail-grid"><div><smallإ>إجمالي المدة</small><b>${s.total} يوم</b></div><div><small>اليوم</small><b>${Math.max(1,s.passed+1)}</b></div><div><small>الحصاد المتوقع</small><b>${fmtDate(s.harvest)}</b></div></div><div class="growth-actions"><button class="secondary" id="detailEdit">✏️ تعديل</button><button class="secondary" id="exportPdf">📄 PDF</button>${g.status==='harvested'?'<button class="danger" id="detailDelete">حذف</button>':'<button class="primary" id="markHarvest">🏁 تسجيل الحصاد</button>'}</div>`;$('#detailEdit').onclick=()=>groupModal(g);const h=$('#markHarvest');if(h)h.onclick=()=>harvestGroup(g.id);const d=$('#detailDelete');if(d)d.onclick=()=>deleteGroup(g.id);const pdf=$('#exportPdf');if(pdf)pdf.onclick=()=>printGrowthReport(g,s,ds);}

function printGrowthReport(g,s,ds){const rows=(growthState.records||[]).map(r=>`<tr><td>${r.date||''}</td><td>${numCell(r.phBefore)}</td><td>${numCell(r.phAfter)}</td><td>${numCell(r.ecBefore)}</td><td>${numCell(r.ecAfter)}</td></tr>`).join('');const w=window.open('','_blank','width=900,height=700');if(!w){toast('اسمح بالنوافذ المنبثقة لتصدير PDF');return}w.document.write(`<!doctype html><html dir="rtl"><head><meta charset="utf-8"><title>${escapeHtml(g.name)} - Growth Report</title><style>body{font-family:Arial,sans-serif;padding:30px;color:#17332c}h1{margin-bottom:4px}.meta{color:#66756f;margin-bottom:20px}.card{border:1px solid #dfe9e5;border-radius:14px;padding:15px;margin:12px 0}table{width:100%;border-collapse:collapse}th,td{border:1px solid #dfe9e5;padding:9px;text-align:center}th{background:#eef6f2}.bar{height:12px;background:#e1ebe6;border-radius:8px;overflow:hidden}.bar span{display:block;height:100%;width:${s.cur.progress}%;background:#087f5b}@media print{button{display:none}}</style></head><body><h1>🌱 ${escapeHtml(g.name)}</h1><div class="meta">${g.type==='fruit'?'نبات مثمر':'نبات خضري'} · تاريخ البداية: ${fmtDate(g.seedDate)} · الحصاد المتوقع: ${fmtDate(s.harvest)}</div><div class="card"><b>المرحلة الحالية:</b> ${escapeHtml(s.cur.name)}<p>${s.cur.progress}%</p><div class="bar"><span></span></div></div><div class="card"><h2>مراحل النمو</h2><ul>${ds.map(x=>`<li>${escapeHtml(x.name)} — ${fmtDate(x.start)} → ${fmtDate(x.end)} (${x.days} يوم)</li>`).join('')}</ul></div><div class="card"><h2>سجل pH وEC</h2><table><thead><tr><th>التاريخ</th><th>pH قبل</th><th>pH بعد</th><th>EC قبل</th><th>EC بعد</th></tr></thead><tbody>${rows||'<tr><td colspan="5">لا توجد بيانات</td></tr>'}</tbody></table></div><script>setTimeout(()=>window.print(),300)<\/script></body></html>`);w.document.close();}
function renderLog(g){const records=growthState.records||[];$('#detailContent').innerHTML=`<div class="log-add"><button class="primary full" id="addRecord">＋ تسجيل قياسات اليوم</button></div><div class="log-table-wrap"><table class="log-table"><thead><tr><th>التاريخ</th><th>pH قبل</th><th>pH بعد</th><th>EC قبل</th><th>EC بعد</th><th>إجراء</th></tr></thead><tbody>${records.map(r=>`<tr><td>${fmtDate(r.date)}</td><td>${numCell(r.phBefore)}</td><td>${numCell(r.phAfter)}</td><td>${numCell(r.ecBefore)}</td><td>${numCell(r.ecAfter)}</td><td><button class="mini-action" data-record-edit="${r.id}">✏️</button><button class="mini-action danger-mini" data-record-delete="${r.id || r.date}">🗑️</button></td></tr>`).join('')||'<tr><td colspan="6">لا توجد قياسات مسجلة بعد.</td></tr>'}</tbody></table></div>`;$('#addRecord').onclick=()=>recordEntry(g.id,true);$('#detailContent').onclick=e=>{const edit=e.target.closest('[data-record-edit]');if(edit){const r=records.find(x=>x.id===edit.dataset.recordEdit);if(r)recordEntry(g.id,true,r);return}const del=e.target.closest('[data-record-delete]');if(del){e.preventDefault();e.stopPropagation();deleteRecord(g.id,del.dataset.recordDelete);return; }};}
function numCell(v){return Number.isFinite(Number(v))?Number(v).toFixed(2):'—';}
function renderReminder(g){const due=g.reminderEnabled!==false;$('#detailContent').innerHTML=`<div class="reminder-card"><div class="reminder-icon">⏰</div><div><b>${due?'التذكير اليومي مفعّل':'التذكير متوقف'}</b><small>الوقت: ${g.reminderTime||'09:00'}</small></div></div><label>وقت التذكير<input id="editReminderTime" type="time" value="${g.reminderTime||'09:00'}"></label><label class="check"><input id="editReminderEnabled" type="checkbox" ${due?'checked':''}> تفعيل التذكير</label><button class="primary full" id="saveReminder">حفظ إعداد التذكير</button>`;$('#saveReminder').onclick=async()=>{try{await setDoc(doc(db,'users',auth.currentUser.uid,'growthGroups',g.id),{reminderTime:$('#editReminderTime').value,reminderEnabled:$('#editReminderEnabled').checked,updatedAt:serverTimestamp()},{merge:true});toast('تم حفظ التذكير');await loadGroups();const ng=growthState.groups.find(x=>x.id===g.id);if(ng)renderGrowthDetail(ng);}catch(e){toast('فشل حفظ التذكير');console.error(e)}}}
async function recordEntry(id,fromDetail=false,existing=null){const g=growthState.groups.find(x=>x.id===id);if(!g)return;const recordId=existing?.id||todayISO();$('#modal').innerHTML=`<div class="modal-box"><div class="modal-top"><h2>🧪 ${existing?'تعديل القياسات':'تسجيل قياسات اليوم'}</h2><button class="modal-x" id="recordClose">×</button></div><label>التاريخ<input id="rDate" type="date" value="${existing?.date||todayISO()}"></label><div class="metric-grid"><label>pH قبل<input id="rPhBefore" type="number" step="0.01" min="0" max="14" value="${existing?.phBefore??''}"></label><label>pH بعد<input id="rPhAfter" type="number" step="0.01" min="0" max="14" value="${existing?.phAfter??''}"></label><label>EC قبل<input id="rEcBefore" type="number" step="0.01" min="0" value="${existing?.ecBefore??''}"></label><label>EC بعد<input id="rEcAfter" type="number" step="0.01" min="0" value="${existing?.ecAfter??''}"></label></div><p id="recordErr" class="hint"></p><div class="modal-actions"><button id="recordCancel" class="secondary">إلغاء</button><button id="recordSave" class="primary">حفظ</button></div></div>`;$('#modal').classList.remove('hidden');$('#modal').style.display='grid';$('#recordClose').onclick=closeModal;$('#recordCancel').onclick=closeModal;$('#recordSave').onclick=async()=>{const err=$('#recordErr');const date=$('#rDate').value;const p1=$('#rPhBefore').value,p2=$('#rPhAfter').value,e1=$('#rEcBefore').value,e2=$('#rEcAfter').value;if(!date||[p1,p2,e1,e2].some(v=>v==='')){err.textContent='يرجى إدخال التاريخ وجميع القيم';return}const vals=[p1,p2].map(Number),ecs=[e1,e2].map(Number);if(vals.some(v=>v<0||v>14)||ecs.some(v=>v<0)){err.textContent='تحقق من قيم pH وEC';return}$('#recordSave').disabled=true;try{const refId=existing?.id||date;await setDoc(doc(db,'users',auth.currentUser.uid,'growthGroups',id,'records',refId),{date,phBefore:vals[0],phAfter:vals[1],ecBefore:ecs[0],ecAfter:ecs[1],createdAt:existing?.createdAt||serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});toast(existing?'تم تحديث القياسات':'تم تسجيل القياسات');growthState.records=await loadRecords(id);closeModal();if(fromDetail)renderGrowthDetail(g);else await loadGroups();}catch(err2){err.textContent='فشل الحفظ: '+(err2.code||err2.message);$('#recordSave').disabled=false;console.error(err2)}};}
async function deleteRecord(groupId,recordId){
  if(!auth.currentUser){toast('انتهت جلسة الدخول');return false}
  if(!groupId||!recordId){toast('معرف القياس غير صالح');return false}
  if(!confirm('حذف هذه القياسات؟ لا يمكن التراجع.'))return false;
  const uid=auth.currentUser.uid;
  const ref=doc(db,'users',uid,'growthGroups',String(groupId),'records',String(recordId));
  console.log('Growth DELETE:',ref.path);
  toast('جاري حذف القياس…');
  try{
    // Firebase documents this as the correct Web API for deleting a document.
    await deleteDoc(ref);
    growthState.records=await loadRecords(groupId);
    const stillThere=growthState.records.some(r=>String(r.id)===String(recordId));
    if(stillThere){
      toast('لم يتم حذف السجل من Firestore');
      console.error('Delete verification failed',ref.path);
      return false;
    }
    const g=growthState.groups.find(x=>String(x.id)===String(groupId));
    if(g){renderGrowthDetail(g);setTimeout(()=>{const tab=$('.detail-tabs button[data-detail-tab="log"]');if(tab)tab.click()},0)}
    toast('تم حذف القياسات بنجاح');
    return true;
  }catch(e){
    console.error('Firestore delete record failed:',e);
    const code=e?.code||'unknown';
    const msg=e?.message||String(e);
    toast('فشل الحذف: '+code);
    alert('فشل حذف القياسات\n\nرمز الخطأ: '+code+'\n'+msg);
    return false;
  }
}
async function harvestGroup(id){const g=growthState.groups.find(x=>x.id===id);if(!g)return;if(!confirm(`هل تريد تسجيل حصاد «${g.name}»؟`))return;try{await setDoc(doc(db,'users',auth.currentUser.uid,'growthGroups',id),{status:'harvested',harvestDate:todayISO(),updatedAt:serverTimestamp()},{merge:true});toast('تم نقل المجموعة إلى Previous Crops');closeModal();await loadGroups();}catch(e){toast('فشل تسجيل الحصاد');console.error(e)}}
async function deleteGroup(id){if(!confirm('حذف المجموعة وسجلها؟ لا يمكن التراجع.'))return;try{await deleteDoc(doc(db,'users',auth.currentUser.uid,'growthGroups',id));toast('تم حذف المجموعة');closeModal();await loadGroups();}catch(e){toast('فشل الحذف');console.error(e)}}
document.addEventListener('click',e=>{const open=e.target.closest('[data-growth-open]');if(open){openGrowthGroup(open.dataset.growthOpen);return}const edit=e.target.closest('[data-growth-edit]');if(edit){const g=growthState.groups.find(x=>x.id===edit.dataset.growthEdit);if(g)groupModal(g);return}const del=e.target.closest('[data-growth-delete]');if(del){deleteGroup(del.dataset.growthDelete);return}});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkGrowthReminder();});function checkGrowthReminder(){const now=new Date(),hm=now.toTimeString().slice(0,5),date=todayISO();growthState.groups.filter(g=>g.status!=='harvested'&&g.reminderEnabled!==false&&g.reminderTime===hm).forEach(g=>{const k=`growth-reminder-${g.id}-${date}`;if(localStorage.getItem(k))return;localStorage.setItem(k,'1');toast(`⏰ تذكير ${g.name}: سجّل pH وEC اليوم`);if('Notification'in window&&Notification.permission==='granted')new Notification(`🌱 ${g.name}`,{body:'حان وقت تسجيل pH وEC اليوم'});});}setInterval(checkGrowthReminder,30000);
function chart(canvas){const c=canvas.getContext('2d'),w=canvas.width=canvas.clientWidth*devicePixelRatio,h=canvas.height=170*devicePixelRatio;c.clearRect(0,0,w,h);const vals=history.map(x=>Number(x.airTemperature)).filter(Number.isFinite);if(vals.length<2)return;c.beginPath();vals.forEach((v,i)=>{const x=i/(vals.length-1)*w,y=h-((v-15)/30)*h;i?c.lineTo(x,y):c.moveTo(x,y)});c.strokeStyle='#087f5b';c.lineWidth=3*devicePixelRatio;c.stroke()}setInterval(()=>{chart($('#tempChart'));chart($('#dataChart'))},1000);
document.addEventListener('DOMContentLoaded',()=>{const m=document.getElementById('modal');if(m)m.style.display='none';});
onAuthStateChanged(auth,u=>{if(!u){showLogin();return}hideLogin();$('#userEmail').textContent=u.email;applyTheme();applyLang();render();if(M.password())setTimeout(()=>M.connect(),500)});applyTheme();
