import {auth,db,onAuthStateChanged,signInWithEmailAndPassword,signOut,collection,doc,setDoc,getDocs,serverTimestamp} from './firebase.js';import * as M from './mqtt.js';
const I={ar:{appSubtitle:'التحكم الذكي في الزراعة المائية',monitoring:'المراقبة',quickControl:'التحكم السريع',airTemp:'حرارة الهواء',data:'البيانات',control:'التحكم',alerts:'التنبيهات',settings:'الإعدادات',systemMode:'وضع النظام',language:'اللغة',theme:'المظهر',mqttPassword:'كلمة مرور MQTT',rememberMqtt:'تذكر كلمة المرور على هذا الجهاز',saveConnect:'حفظ والاتصال',logout:'تسجيل الخروج',home:'الرئيسية',growth:'نمو النباتات',growthSubtitle:'متابعة المراحل والتذكيرات والتسجيل اليدوي',newGroup:'مجموعة جديدة'},en:{appSubtitle:'Smart hydroponic control',monitoring:'Monitoring',quickControl:'Quick control',airTemp:'Air Temperature',data:'Data',control:'Control',alerts:'Alerts',settings:'Settings',systemMode:'System mode',language:'Language',theme:'Theme',mqttPassword:'MQTT password',rememberMqtt:'Remember password on this device',saveConnect:'Save & Connect',logout:'Sign out',home:'Home',growth:'Plant Growth',growthSubtitle:'Stages, reminders and manual records',newGroup:'New Group'},fr:{appSubtitle:'Contrôle hydroponique intelligent',monitoring:'Surveillance',quickControl:'Contrôle rapide',airTemp:'Température de l’air',data:'Données',control:'Contrôle',alerts:'Alertes',settings:'Paramètres',systemMode:'Mode système',language:'Langue',theme:'Thème',mqttPassword:'Mot de passe MQTT',rememberMqtt:'Mémoriser sur cet appareil',saveConnect:'Enregistrer et connecter',logout:'Déconnexion',home:'Accueil',growth:'Croissance des plantes',growthSubtitle:'Étapes, rappels et relevés manuels',newGroup:'Nouveau groupe'}};
let lang=localStorage.getItem('hydro_lang')||'ar',mode=localStorage.getItem('hydro_mode')||'AUTO',tele={airTemperature:null,airHumidity:null,waterTemperature:null,waterLevel:null,ph:null,ec:null},history=[];const limits={airTemperature:[28,30],airHumidity:[75,80],waterTemperature:[18,28],waterLevel:[20,40]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}function t(k){return I[lang][k]||I.ar[k]||k}function applyLang(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';$$('[data-i18n]').forEach(e=>e.textContent=t(e.dataset.i18n));$('#language').value=lang;localStorage.setItem('hydro_lang',lang)}
function page(p){$$('.page').forEach(e=>e.classList.toggle('active',e.id===p));$$('.nav').forEach(e=>e.classList.toggle('active',e.dataset.page===p));if(p==='growth')loadGroups()}$$('.nav').forEach(b=>b.onclick=()=>page(b.dataset.page));$$('[data-open]').forEach(b=>b.onclick=()=>page(b.dataset.open));$$('[data-back]').forEach(b=>b.onclick=()=>page(b.dataset.back));
function gauge(key,label,icon,unit,min,max){const v=tele[key];let pct=v==null?0:Math.max(0,Math.min(100,(v-min)/(max-min)*100));const bad=v!=null&&((key==='airTemperature'&&v>=limits.airTemperature[1])||(key==='airHumidity'&&v>=limits.airHumidity[1])||(key==='waterTemperature'&&v>=limits.waterTemperature[1])||(key==='waterLevel'&&v<=limits.waterLevel[0]));return `<article class="gauge-card ${bad?'danger-gauge':''}"><div class="gauge" style="--pct:${pct}%;--gcolor:${bad?'var(--red)':key==='airTemperature'?'var(--orange)':'var(--green)'}"><div class="gauge-inner"><div class="gauge-value">${v==null?'—':Number(v).toFixed(key==='airHumidity'||key==='waterLevel'?0:1)}${v==null?'':unit}</div></div></div><div class="gauge-label">${icon} ${label}</div><div class="gauge-status">${bad?'⚠️ '+(lang==='ar'?'خارج النطاق':lang==='fr'?'Hors plage':'Out of range'):v==null?'—':lang==='ar'?'طبيعي':lang==='fr'?'Normal':'Normal'}</div></article>`}
function render(){const g=$('#gauges');g.innerHTML=gauge('airTemperature',t('airTemp'),'🌡️','°C',10,45)+gauge('airHumidity',lang==='ar'?'الرطوبة':lang==='fr'?'Humidité':'Humidity','💧','%',0,100)+gauge('waterTemperature',lang==='ar'?'حرارة الماء':lang==='fr'?'Température de l’eau':'Water Temperature','🌊','°C',5,40)+gauge('waterLevel',lang==='ar'?'مستوى الخزان':lang==='fr'?'Niveau du réservoir':'Water Level','💦','%',0,100)+gauge('ph','pH','🧪','',3,10)+gauge('ec','EC','⚡','',0,4);$('#modeBadge').textContent=mode;$('#modeBadge').className='badge '+(mode==='MANUAL'?'manual':'auto');$('#controls').innerHTML=devices().map(d=>`<div class="device panel"><div><b>${d.icon} ${d.name}</b><small>${d.sub}</small></div><button class="switch ${d.on?'on':''}" data-device="${d.id}"></button></div>`).join('');$('#quickDevices').innerHTML=devices().slice(0,3).map(d=>`<div class="quick-row"><span>${d.icon} ${d.name}</span><button class="switch ${d.on?'on':''}" data-device="${d.id}"></button></div>`).join('');$$('[data-device]').forEach(b=>b.onclick=()=>toggleDevice(b.dataset.device));$('#userEmail').textContent=auth.currentUser?.email||'—';applyLang()}
function devices(){return[{id:'pump1',name:'Pump 1 — NFT',sub:'ON/OFF cycle',icon:'💧',on:false},{id:'pump2',name:'Pump 2 — Venturi',sub:'ON/OFF cycle',icon:'🌀',on:false},{id:'pump3',name:'Pump 3 — Tank Fill',sub:'20% ON / 40% OFF',icon:'🚰',on:false},{id:'pump4',name:'Pump 4 — Pad Cooling',sub:'Temperature + Humidity',icon:'❄️',on:false},{id:'fan1',name:'Fan 1',sub:'Temperature + Humidity',icon:'🌀',on:false},{id:'fan2',name:'Fan 2',sub:'ON/OFF cycle',icon:'🌀',on:false}]}
function toggleDevice(id){if(mode==='AUTO'){toast(lang==='ar'?'النظام في AUTO — انتقل إلى MANUAL أولًا':lang==='fr'?'Le système est en AUTO — passez en MANUAL':'System is AUTO — switch to MANUAL first');return}if(!M.publish({type:'device',device:id,state:'TOGGLE'}))toast(lang==='ar'?'MQTT غير متصل': 'MQTT offline')}
$('#autoBtn').onclick=()=>setMode('AUTO');$('#manualBtn').onclick=()=>{showConfirm(()=>setMode('MANUAL'))};function setMode(m){mode=m;localStorage.setItem('hydro_mode',m);M.publish({type:'mode',mode:m});render();toast(m==='AUTO'?(lang==='ar'?'تم تفعيل AUTO':'AUTO enabled'):(lang==='ar'?'تم تفعيل MANUAL':'MANUAL enabled'))}function showConfirm(ok){$('#modal').innerHTML=`<div class="modal-box"><h3>⚠️ ${lang==='ar'?'التحكم اليدوي':lang==='fr'?'Contrôle manuel':'Manual control'}</h3><p>${lang==='ar'?'تأكد من أن تشغيل الأجهزة آمن.':lang==='fr'?'Assurez-vous que le fonctionnement est sûr.':'Make sure operating the devices is safe.'}</p><div class="modal-actions"><button class="danger" id="cancel">${lang==='ar'?'إلغاء':'Cancel'}</button><button class="primary" id="continue">${lang==='ar'?'متابعة':'Continue'}</button></div></div>`;$('#modal').classList.remove('hidden');$('#modal').style.display='grid';$('#cancel').onclick=closeModal;$('#continue').onclick=()=>{closeModal();ok()}}function closeModal(){const m=$('#modal');m.classList.add('hidden');m.style.display='none'}
window.addEventListener('mqtt-status',e=>{const c=e.detail.connected;$('#mqttDot').className='dot '+(c?'on':'off');$('#mqttState').textContent=c?(lang==='ar'?'متصل بـ MQTT':'MQTT Connected'):(e.detail.needsPassword?(lang==='ar'?'أدخل كلمة مرور MQTT':'Enter MQTT password'):(lang==='ar'?'غير متصل':'Offline'));if(c)toast(lang==='ar'?'تم الاتصال بـ HiveMQ':'Connected to HiveMQ')});window.addEventListener('mqtt-message',e=>{if(e.detail.topic===M.TOPICS.sensors){tele={...tele,...e.detail.data};history.push({...tele,time:new Date()});if(history.length>100)history.shift();$('#lastUpdate').textContent=(lang==='ar'?'آخر تحديث ':'Last update ')+new Date().toLocaleTimeString();render()}});
$('#mqttSave').onclick=()=>{const p=$('#mqttPassword').value;if(!p&& !M.password()){toast(lang==='ar'?'أدخل كلمة مرور MQTT أولًا':'Enter MQTT password first');return}M.save(p||M.password(),$('#mqttRemember').checked);M.connect()};$('#language').onchange=e=>{lang=e.target.value;applyLang();render()};$('#theme').onchange=e=>{localStorage.setItem('hydro_theme',e.target.value);applyTheme()};function applyTheme(){const x=localStorage.getItem('hydro_theme')||'system';document.body.classList.toggle('dark',x==='dark'||(x==='system'&&matchMedia('(prefers-color-scheme: dark)').matches))}$('#logout').onclick=()=>signOut(auth);
function showLogin(){
  let overlay=document.getElementById('loginOverlay');
  if(!overlay){
    overlay=document.createElement('div');
    overlay.id='loginOverlay';
    overlay.className='modal';
    document.body.appendChild(overlay);
  }
  overlay.innerHTML=`<div class="modal-box"><h2>🌱 Hydroponic Control</h2><p>${lang==='ar'?'تسجيل الدخول':'Sign in'}</p><label>Email<input id="loginEmail" type="email" autocomplete="email"></label><label>Password<input id="loginPass" type="password" autocomplete="current-password"></label><button id="loginBtn" class="primary full">${lang==='ar'?'دخول':'Sign in'}</button><p id="loginErr" class="hint"></p></div>`;
  overlay.classList.remove('hidden');
  document.getElementById('app').style.display='none';
  $('#loginBtn').onclick=async()=>{
    const email=$('#loginEmail').value.trim(), password=$('#loginPass').value;
    if(!email||!password){$('#loginErr').textContent=lang==='ar'?'أدخل البريد وكلمة المرور':'Enter email and password';return}
    $('#loginBtn').disabled=true;
    try{await signInWithEmailAndPassword(auth,email,password)}
    catch(e){$('#loginErr').textContent=(e.code||e.message);$('#loginBtn').disabled=false}
  };
}
function hideLogin(){const overlay=document.getElementById('loginOverlay');if(overlay)overlay.classList.add('hidden');document.getElementById('app').style.display='block'}
const veg=[['seed','البذرة',1],['germination','الإنبات',5],['transplant','التشتيل',12],['vegetative','النمو الخضري',45],['harvest','الحصاد',0]],fruit=[['seed','البذرة',1],['germination','الإنبات',5],['transplant','التشتيل',12],['vegetative','النمو الخضري',45],['flowering','التزهير',20],['fruiting','الإثمار',30],['harvest','الحصاد',0]];
async function loadGroups(){if(!auth.currentUser)return;const snap=await getDocs(collection(db,'users',auth.currentUser.uid,'growthGroups'));const arr=[];snap.forEach(x=>arr.push({id:x.id,...x.data()}));$('#groups').innerHTML=arr.map(g=>`<div class="group"><b>🌱 ${g.name}</b><small>${g.type==='fruit'?'🍅':'🥬'} • ${g.seedDate||''}</small>${(g.stages||[]).map(s=>`<div class="stage"><span>${s.name}</span><span>${s.days} يوم</span></div>`).join('')}<button class="primary full" data-record="${g.id}">تسجيل pH / EC اليوم</button></div>`).join('')||'<div class="panel">لا توجد مجموعات بعد</div>';$$('[data-record]').forEach(b=>b.onclick=()=>recordEntry(b.dataset.record))}
document.addEventListener('click',e=>{const b=e.target.closest('#newGroup');if(b){e.preventDefault();e.stopPropagation();groupModal();}});function groupModal(){const stages=[...veg];$('#modal').innerHTML=`<div class="modal-box"><h2>🌱 ${t('newGroup')}</h2><label>اسم المجموعة<input id="gName" value="مجموعة جديدة"></label><label>نوع النبات<select id="gType"><option value="vegetable">🥬 نبات خضري</option><option value="fruit">🍅 نبات مثمر</option></select></label><label>تاريخ وضع البذرة<input id="gDate" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>وقت التذكير<input id="gTime" type="time" value="09:00"></label><div id="stageEditor"></div><button id="addStage" class="primary full">＋ إضافة مرحلة</button><div class="modal-actions"><button id="gCancel" class="danger">إلغاء</button><button id="gSave" class="primary">حفظ</button></div><p id="gErr" class="hint"></p></div>`;function draw(){const s=$('#gType').value==='fruit'?fruit:veg;$('#stageEditor').innerHTML=s.map((x,i)=>`<label>${i+1}. ${x[1]}<input class="stageDays" data-name="${x[1]}" type="number" min="0" value="${x[2]}"></label>`).join('')}draw();$('#gType').onchange=draw;$('#gCancel').onclick=closeModal;$('#gSave').onclick=saveGroup;$('#addStage').onclick=()=>{$('#stageEditor').insertAdjacentHTML('beforeend',`<label>مرحلة جديدة<input class="stageDays" data-name="مرحلة جديدة" type="number" min="0" value="1"></label>`)}}async function saveGroup(){const err=$('#gErr');try{if(!auth.currentUser)throw new Error('NOT_AUTHENTICATED');const id=crypto.randomUUID();const stages=$$('.stageDays').map(x=>({name:x.dataset.name,days:Number(x.value)||0}));const data={name:$('#gName').value.trim()||'مجموعة',type:$('#gType').value,seedDate:$('#gDate').value,reminderTime:$('#gTime').value,stages,createdAt:serverTimestamp(),ownerUid:auth.currentUser.uid};await setDoc(doc(db,'users',auth.currentUser.uid,'growthGroups',id),data);closeModal();toast(lang==='ar'?'تم حفظ المجموعة بنجاح':'Group saved successfully');loadGroups()}catch(e){err.textContent=(lang==='ar'?'فشل الحفظ: ':'Save failed: ')+(e.code||e.message);console.error(e)}}async function recordEntry(id){const p=prompt('pH قبل التعديل');if(p===null)return;const e=prompt('EC قبل التعديل');if(e===null)return;const pa=prompt('pH بعد التعديل');if(pa===null)return;const ea=prompt('EC بعد التعديل');if(ea===null)return;await setDoc(doc(db,'users',auth.currentUser.uid,'growthGroups',id,'records',new Date().toISOString().slice(0,10)),{date:new Date().toISOString().slice(0,10),phBefore:Number(p),ecBefore:Number(e),phAfter:Number(pa),ecAfter:Number(ea)});toast(lang==='ar'?'تم تسجيل القيم':'Values saved')}
function chart(canvas){const c=canvas.getContext('2d'),w=canvas.width=canvas.clientWidth*devicePixelRatio,h=canvas.height=170*devicePixelRatio;c.clearRect(0,0,w,h);const vals=history.map(x=>Number(x.airTemperature)).filter(Number.isFinite);if(vals.length<2)return;c.beginPath();vals.forEach((v,i)=>{const x=i/(vals.length-1)*w,y=h-((v-15)/30)*h;i?c.lineTo(x,y):c.moveTo(x,y)});c.strokeStyle='#087f5b';c.lineWidth=3*devicePixelRatio;c.stroke()}setInterval(()=>{chart($('#tempChart'));chart($('#dataChart'))},1000);
document.addEventListener('DOMContentLoaded',()=>{const m=document.getElementById('modal');if(m)m.style.display='none';});
onAuthStateChanged(auth,u=>{if(!u){showLogin();return}hideLogin();$('#userEmail').textContent=u.email;applyTheme();applyLang();render();if(M.password())setTimeout(()=>M.connect(),500)});applyTheme();
